import React from 'react';
import { useApp } from '../context/AppContext';
import { 
  Users, 
  Trophy, 
  AlertTriangle, 
  Activity, 
  ShieldCheck, 
  TrendingUp, 
  Award, 
  Brain, 
  Layers, 
  ArrowLeft, 
  MessageSquare,
  Sparkles,
  Percent,
  GraduationCap,
  Download,
  Database,
  Terminal,
  Play,
  Copy,
  Check,
  Upload
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer, 
  Cell 
} from 'recharts';

const IconHelper = ({ name }) => {
  const sizeClass = "w-6 h-6";
  switch (name) {
    case 'alert-triangle':
      return <AlertTriangle className={`${sizeClass} text-[#ff5252] text-glow-red`} />;
    case 'shield-check':
      return <ShieldCheck className={`${sizeClass} text-mintGreen text-glow-mint`} />;
    case 'trending-up':
      return <TrendingUp className={`${sizeClass} text-electricBlue text-glow-blue`} />;
    case 'award':
      return <Award className={`${sizeClass} text-accentViolet text-glow-violet`} />;
    case 'brain':
      return <Brain className={`${sizeClass} text-accentViolet text-glow-violet`} />;
    default:
      return <Activity className={`${sizeClass} text-electricBlue`} />;
  }
};

const CustomTooltip = ({ active, payload }) => {
  if (active && payload && payload.length) {
    return (
      <div className="bg-[#0a0c16]/95 border border-electricBlue/20 p-3 rounded-lg shadow-xl backdrop-blur-md text-xs">
        <p className="font-semibold text-white mb-1 uppercase tracking-wider">{payload[0].payload.name}</p>
        <p className="text-electricBlue">
          Correlation Weight: <strong className="text-glow-blue">{payload[0].value}%</strong>
        </p>
      </div>
    );
  }
  return null;
};

const InsightsView = () => {
  const { 
    insights, 
    resetApp, 
    setIsChatOpen, 
    fileInfo,
    sqlQuery,
    setSqlQuery,
    sqlResults,
    setSqlResults,
    sqlLoading,
    sqlError,
    runSqlQuery,
    uploadFile,
    analyseData
  } = useApp();

  const [tempQuery, setTempQuery] = React.useState('');
  const [copied, setCopied] = React.useState(false);
  const [showUploader, setShowUploader] = React.useState(false);
  const [localLoading, setLocalLoading] = React.useState(false);
  const fileInputRef = React.useRef(null);

  const handleFileImport = async (e) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setLocalLoading(true);
      try {
        await uploadFile(file);
        await analyseData();
      } catch (err) {
        alert("Failed to upload CSV: " + err.message);
      } finally {
        setLocalLoading(false);
        setShowUploader(false);
      }
    }
  };

  const handleQuerySubmit = (e) => {
    e.preventDefault();
    if (!tempQuery.trim() || sqlLoading) return;
    runSqlQuery(tempQuery);
  };

  if (!insights) {
    return (
      <div className="flex flex-col items-center justify-center flex-1 py-16">
        <Activity className="w-16 h-16 text-electricBlue animate-spin mb-4" />
        <p className="text-gray-400">Syncing telemetry data orbits...</p>
      </div>
    );
  }

  const { kpis, factors, distributions, insight_cards } = insights;

  const downloadReport = () => {
    let report = `# DataOrbit Academy Intelligence Report\n`;
    report += `Source File: ${fileInfo?.filename || 'Mock Space Cohort Telemetry'}\n`;
    report += `Date Compiled: ${new Date().toLocaleDateString()}\n\n`;
    
    report += `## Key Performance Indicators\n`;
    report += `- **Total Active Cohort Students**: ${kpis.total_students}\n`;
    report += `- **Average Exam Score**: ${kpis.avg_score}%\n`;
    report += `- **At-Risk Student Count**: ${kpis.at_risk_count}\n`;
    report += `- **Top Performance Driver**: ${kpis.top_factor}\n\n`;
    
    report += `## Department Telemetry Summary\n`;
    distributions.forEach(d => {
      report += `- **${d.category}**: ${d.student_count} students | Avg GPA: ${d.avg_gpa}/10.0 | Avg Attendance: ${d.avg_attendance}%\n`;
    });
    report += `\n`;
    
    report += `## Automated AI Observations\n`;
    insight_cards.forEach(card => {
      report += `### ${card.headline}\n`;
      report += `${card.explanation}\n\n`;
    });
    
    report += `\n---\nReport generated by DataOrbit Platform.\n`;
    
    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `DataOrbit_Academy_Report_${fileInfo?.filename?.split('.')[0] || 'telemetry'}.md`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Chart colors aligned with Beach White & English Blue theme
  const colors = ['#1b3a5b', '#2b4c7e', '#4a607a', '#6b7280', '#9ca3af'];

  return (
    <div className="flex-1 w-full max-w-6xl mx-auto px-4 py-8 flex flex-col space-y-8 animate-card-entrance">
      
      {/* Top Navbar Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-electricBlue/15 pb-5">
        <div>
          <span className="text-xs font-semibold uppercase tracking-widest text-electricBlue px-2.5 py-1 bg-electricBlue/10 border border-electricBlue/25 rounded-full">
            Platform Telemetry
          </span>
          <h2 className="text-2xl font-bold tracking-tight text-white mt-2">
            Academy Intelligence Report
          </h2>
          <p className="text-gray-400 text-xs mt-0.5 font-medium truncate max-w-md">
            Source: {fileInfo?.filename || 'Mock Space Cohort Telemetry'}
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
          <button
            onClick={downloadReport}
            className="flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-semibold rounded-xl bg-white/[0.04] border border-mintGreen/25 hover:bg-mintGreen/10 hover:border-mintGreen/45 text-mintGreen transition-all w-full sm:w-auto"
          >
            <Download className="w-4 h-4" />
            Download Report
          </button>
          <button
            onClick={resetApp}
            className="flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-semibold rounded-xl bg-white/[0.04] border border-electricBlue/15 hover:bg-white/[0.08] hover:border-electricBlue/30 text-white transition-all w-full sm:w-auto"
          >
            <ArrowLeft className="w-4 h-4" />
            Upload New
          </button>
          <button
            onClick={() => setIsChatOpen(true)}
            className="flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-semibold rounded-xl bg-gradient-to-r from-electricBlue to-accentViolet text-spaceBg hover:brightness-110 active:scale-95 shadow-[0_0_15px_rgba(79,195,247,0.2)] transition-all w-full sm:w-auto"
          >
            <MessageSquare className="w-4 h-4" />
            Query AI Agent
          </button>
        </div>
      </div>

      {/* Subtle Import Document Section */}
      <div className="glass-card p-3.5 flex flex-col space-y-2.5">
        <div 
          onClick={() => setShowUploader(!showUploader)}
          className="flex items-center justify-between cursor-pointer text-gray-500 hover:text-electricBlue transition-all"
        >
          <div className="flex items-center space-x-2.5 text-xs font-bold uppercase tracking-wider">
            <Upload className="w-4 h-4 text-accentViolet" />
            <span>Import/Upload New CSV Document</span>
          </div>
          <span className="text-xs text-gray-400 font-mono font-semibold">
            {showUploader ? '▲ Close' : '▼ Expand'}
          </span>
        </div>
        
        {showUploader && (
          <div 
            onClick={() => fileInputRef.current.click()}
            className="pt-2 border-t border-gray-100 flex flex-col items-center justify-center p-6 border-2 border-dashed border-gray-200 rounded-xl bg-gray-50/50 hover:bg-gray-50/80 transition-all cursor-pointer"
          >
            <input 
              type="file"
              ref={fileInputRef}
              accept=".csv"
              onChange={handleFileImport}
              className="hidden"
            />
            {localLoading ? (
              <div className="flex items-center space-x-2 text-xs font-semibold text-electricBlue">
                <div className="w-4 h-4 border-2 border-electricBlue border-t-transparent rounded-full animate-spin" />
                <span>Loading & Parsing Telemetry Data...</span>
              </div>
            ) : (
              <div className="flex flex-col items-center space-y-1.5 text-center">
                <Upload className="w-6 h-6 text-electricBlue animate-bounce" />
                <span className="text-xs font-semibold text-white">Click to Select CSV Telemetry File</span>
                <span className="text-[10px] text-gray-400 font-medium">Accepts standard .csv table vectors</span>
              </div>
            )}
          </div>
        )}
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        
        {/* KPI 1: Total Students */}
        <div className="glass-card p-5 relative overflow-hidden group">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-400 text-xs font-semibold uppercase tracking-wider mb-2">Total Students</p>
              <h3 className="text-3xl font-bold text-glow-mint text-mintGreen">{kpis.total_students}</h3>
            </div>
            <div className="p-2.5 bg-mintGreen/10 border border-mintGreen/25 rounded-xl">
              <Users className="w-5 h-5 text-mintGreen" />
            </div>
          </div>
          <p className="text-[10px] text-gray-500 mt-4 tracking-wider uppercase font-medium">Active Academy Cohorts</p>
          <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-mintGreen/5 to-mintGreen/30 opacity-50" />
        </div>

        {/* KPI 2: Avg Score */}
        <div className="glass-card p-5 relative overflow-hidden group">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-400 text-xs font-semibold uppercase tracking-wider mb-2">Average Score</p>
              <h3 className="text-3xl font-bold text-glow-blue text-electricBlue">{kpis.avg_score}%</h3>
            </div>
            <div className="p-2.5 bg-electricBlue/10 border border-electricBlue/25 rounded-xl">
              <Trophy className="w-5 h-5 text-electricBlue" />
            </div>
          </div>
          <p className="text-[10px] text-gray-500 mt-4 tracking-wider uppercase font-medium">Exam Performance Telemetry</p>
          <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-electricBlue/5 to-electricBlue/30 opacity-50" />
        </div>

        {/* KPI 3: At-Risk Count */}
        <div className="glass-card p-5 relative overflow-hidden group">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-400 text-xs font-semibold uppercase tracking-wider mb-2">At-Risk Count</p>
              <h3 className="text-3xl font-bold text-glow-red text-[#ff5252]">{kpis.at_risk_count}</h3>
            </div>
            <div className="p-2.5 bg-red-500/10 border border-red-500/25 rounded-xl">
              <AlertTriangle className="w-5 h-5 text-[#ff5252]" />
            </div>
          </div>
          <p className="text-[10px] text-gray-500 mt-4 tracking-wider uppercase font-medium">Warning: GPA &lt; 5.0 or Att. &lt; 40%</p>
          <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-red-500/5 to-[#ff5252]/30 opacity-50" />
        </div>

        {/* KPI 4: Top Factor */}
        <div className="glass-card p-5 relative overflow-hidden group">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-400 text-xs font-semibold uppercase tracking-wider mb-2">Top Factor</p>
              <h3 className="text-lg font-bold text-glow-violet text-accentViolet leading-tight truncate max-w-[150px] mt-1.5">{kpis.top_factor}</h3>
            </div>
            <div className="p-2.5 bg-accentViolet/10 border border-accentViolet/25 rounded-xl">
              <Activity className="w-5 h-5 text-accentViolet" />
            </div>
          </div>
          <p className="text-[10px] text-gray-500 mt-4 tracking-wider uppercase font-medium">Primary Correlation Vector</p>
          <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-accentViolet/5 to-accentViolet/30 opacity-50" />
        </div>
      </div>

      {/* AI SQL Query Console */}
      <div className="glass-card p-6 flex flex-col space-y-4">
        <div className="flex items-center justify-between border-b border-electricBlue/15 pb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-electricBlue/10 border border-electricBlue/25 rounded-xl">
              <Database className="w-5 h-5 text-electricBlue text-glow-blue" />
            </div>
            <div>
              <h4 className="text-base font-semibold uppercase tracking-widest text-white">
                🚀 AI Text-to-SQL Query Console
              </h4>
              <p className="text-xs text-gray-400 mt-1">
                Ask a question in natural language to query the student telemetry database, or write direct SQL queries.
              </p>
            </div>
          </div>
          <Sparkles className="w-5 h-5 text-mintGreen text-glow-mint hidden sm:block animate-pulse" />
        </div>

        {/* Input & Form */}
        <form onSubmit={handleQuerySubmit} className="flex flex-col sm:flex-row gap-3">
          <input
            type="text"
            value={tempQuery}
            onChange={(e) => setTempQuery(e.target.value)}
            placeholder="e.g., Show top 5 students by GPA or SELECT name, gpa FROM students WHERE gpa > 9.0"
            className="flex-1 bg-white/[0.03] border border-electricBlue/15 focus:border-electricBlue/40 focus:bg-white/[0.06] rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-electricBlue/30 transition-all font-medium"
          />
          <button
            type="submit"
            disabled={sqlLoading || !tempQuery.trim()}
            className="flex items-center justify-center gap-2 px-6 py-3 text-sm font-semibold rounded-xl bg-gradient-to-r from-electricBlue to-accentViolet text-spaceBg hover:brightness-110 active:scale-95 disabled:opacity-40 shadow-[0_0_15px_rgba(79,195,247,0.2)] transition-all font-semibold"
          >
            {sqlLoading ? (
              <Activity className="w-4 h-4 animate-spin text-spaceBg" />
            ) : (
              <Play className="w-4 h-4 text-spaceBg fill-current" />
            )}
            <span>Run Query</span>
          </button>
        </form>

        {/* Suggestion Template Pills */}
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <span className="text-gray-500 font-semibold uppercase tracking-wider">Try Asking:</span>
          {[
            "Who has the highest GPA?",
            "Average attendance in Computer Science",
            "Show students with attendance < 50%",
            "List top 5 exam scores in Engineering"
          ].map((sample, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => {
                setTempQuery(sample);
                runSqlQuery(sample);
              }}
              className="px-3 py-1.5 bg-white border border-gray-200 text-gray-500 hover:text-electricBlue hover:border-electricBlue hover:bg-gray-50 rounded-lg transition-all font-medium"
            >
              {sample}
            </button>
          ))}
        </div>

        {/* Results Panel */}
        {sqlResults && (
          <div className="bg-[#05060d] border border-electricBlue/10 rounded-xl overflow-hidden p-4 space-y-4 animate-card-entrance">
            
            {/* Generated SQL info */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white/[0.02] border border-white/5 p-3 rounded-lg text-xs font-mono text-gray-400">
              <div className="flex items-center gap-2 overflow-hidden">
                <Terminal className="w-4 h-4 text-accentViolet flex-shrink-0" />
                <span className="text-glow-violet text-accentViolet font-semibold flex-shrink-0">Generated SQL:</span>
                <span className="text-white select-all truncate">{sqlResults.sql_query}</span>
              </div>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(sqlResults.sql_query);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
                className="flex items-center gap-1 text-[10px] bg-white/[0.04] hover:bg-white/[0.08] border border-white/5 hover:border-white/10 px-2 py-1 rounded transition-all text-gray-400 hover:text-white flex-shrink-0"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-mintGreen" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>

            {/* Answer interpretation */}
            <div className="flex items-start gap-2.5 text-sm leading-relaxed border-b border-white/5 pb-3">
              <Sparkles className="w-4 h-4 text-mintGreen text-glow-mint mt-0.5 flex-shrink-0" />
              <div>
                <span className="font-semibold text-white">Result Answer: </span>
                <span className="text-gray-300 font-medium">{sqlResults.answer}</span>
                <span className="block text-[11px] text-gray-500 mt-1 font-mono">{sqlResults.explanation}</span>
              </div>
            </div>

            {/* Data Table */}
            {sqlResults.records && sqlResults.records.length > 0 ? (
              <div className="overflow-x-auto max-h-60 border border-white/[0.04] rounded-lg">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="bg-[#0b0c16] border-b border-white/10 text-gray-400 font-semibold uppercase tracking-wider">
                      {sqlResults.columns.map((col, cIdx) => (
                        <th key={cIdx} className="px-4 py-3 font-mono">
                          {col.replace('_pct', ' %').replace('_score', ' Score').replace('_', ' ').toUpperCase()}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {sqlResults.records.map((row, rIdx) => (
                      <tr 
                        key={rIdx} 
                        className="border-b border-white/[0.04] hover:bg-white/[0.02] text-gray-200 transition-all font-mono"
                      >
                        {sqlResults.columns.map((col, cIdx) => (
                          <td key={cIdx} className="px-4 py-2.5">
                            {row[col] === null || row[col] === undefined
                              ? 'N/A'
                              : typeof row[col] === 'number'
                              ? row[col] % 1 === 0
                                ? row[col]
                                : row[col].toFixed(2)
                              : row[col].toString()}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="text-center py-6 text-gray-500 text-xs">
                No database records matched this query.
              </div>
            )}
          </div>
        )}
      </div>

      {/* Analytics 2-Column Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Recharts Horizontal Bar Chart */}
        <div className="glass-card p-6 lg:col-span-7 flex flex-col space-y-4">
          <div>
            <h4 className="text-base font-semibold uppercase tracking-widest text-electricBlue">
              Top Factors Affecting Marks
            </h4>
            <p className="text-xs text-gray-400 mt-1">
              Percentage coefficient indicating factor correlation weights against student grades.
            </p>
          </div>

          <div className="h-72 w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={factors}
                layout="vertical"
                margin={{ top: 10, right: 20, left: 10, bottom: 5 }}
              >
                <defs>
                  <linearGradient id="barGrad" x1="0" y1="0" x2="1" y2="0">
                    <stop offset="0%" stopColor="#4a607a" stopOpacity={0.25} />
                    <stop offset="100%" stopColor="#1b3a5b" stopOpacity={0.95} />
                  </linearGradient>
                </defs>
                <XAxis 
                  type="number" 
                  domain={[0, 100]} 
                  stroke="rgba(27, 58, 91, 0.2)"
                  tick={{ fill: '#4a607a', fontSize: 10, fontFamily: 'Inter' }}
                  gridArea=""
                />
                <YAxis 
                  type="category" 
                  dataKey="name" 
                  stroke="rgba(27, 58, 91, 0.2)"
                  tick={{ fill: '#1b3a5b', fontSize: 10, fontFamily: 'Inter' }}
                  width={110}
                />
                <Tooltip content={<CustomTooltip />} cursor={{ fill: 'rgba(255, 255, 255, 0.02)' }} />
                <Bar 
                  dataKey="value" 
                  radius={[0, 8, 8, 0]}
                  barSize={18}
                >
                  {factors.map((entry, index) => (
                    <Cell 
                      key={`cell-${index}`} 
                      fill="url(#barGrad)"
                      stroke="rgba(100, 160, 255, 0.3)"
                      strokeWidth={1}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Right Column: Column Distribution Summary List */}
        <div className="glass-card p-6 lg:col-span-5 flex flex-col space-y-4">
          <div>
            <h4 className="text-base font-semibold uppercase tracking-widest text-accentViolet">
              Department Telemetry
            </h4>
            <p className="text-xs text-gray-400 mt-1">
              Active student cohort distribution, GPA, and attendance averages.
            </p>
          </div>

          <div className="flex-1 overflow-y-auto space-y-3 pr-1 mt-2 max-h-[280px]">
            {distributions && distributions.map((item, idx) => (
              <div 
                key={idx}
                className="bg-[#0b0c16] border border-electricBlue/10 p-3.5 rounded-xl hover:border-electricBlue/30 transition-all flex flex-col space-y-2.5"
              >
                {/* Header */}
                <div className="flex justify-between items-center">
                  <span className="font-semibold text-sm text-glow-blue text-electricBlue truncate max-w-[180px]">{item.category}</span>
                  <span className="text-[10px] text-gray-400 bg-white/[0.04] px-2 py-0.5 rounded border border-white/5 font-medium">
                    {item.student_count} Students
                  </span>
                </div>

                {/* Metrics */}
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="flex flex-col space-y-1">
                    <span className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold">GPA Mean</span>
                    <span className="font-semibold text-white flex items-center gap-1">
                      <GraduationCap className="w-3.5 h-3.5 text-accentViolet" />
                      {item.avg_gpa} / 10.0
                    </span>
                    {/* Visual Bar */}
                    <div className="w-full h-1 bg-white/[0.05] rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-accentViolet rounded-full" 
                        style={{ width: `${(item.avg_gpa / 10.0) * 100}%` }}
                      />
                    </div>
                  </div>

                  <div className="flex flex-col space-y-1">
                    <span className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold">Attendance</span>
                    <span className="font-semibold text-white flex items-center gap-1">
                      <Percent className="w-3.5 h-3.5 text-mintGreen" />
                      {item.avg_attendance}%
                    </span>
                    {/* Visual Bar */}
                    <div className="w-full h-1 bg-white/[0.05] rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-mintGreen rounded-full" 
                        style={{ width: `${item.avg_attendance}%` }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Auto Insights Console */}
      <div className="flex flex-col space-y-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-mintGreen text-glow-mint" />
          <h4 className="text-lg font-bold tracking-tight uppercase text-white font-space">
            Auto Insights Console
          </h4>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {insight_cards && insight_cards.map((card, idx) => (
            <div 
              key={idx}
              className="glass-card p-5 flex flex-col space-y-3 hover:border-mintGreen/30 relative overflow-hidden group"
            >
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-white/[0.04] border border-white/10 rounded-lg group-hover:border-electricBlue/20 transition-all">
                  <IconHelper name={card.icon} />
                </div>
                <h5 className="font-bold text-sm text-white tracking-wide leading-snug truncate">
                  {card.headline}
                </h5>
              </div>
              <p className="text-xs text-gray-400 leading-relaxed font-medium">
                {card.explanation}
              </p>
              
              {/* Corner accent glow indicator */}
              <div className="absolute top-0 right-0 w-8 h-8 bg-gradient-to-bl from-white/[0.02] to-transparent pointer-events-none" />
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};

export default InsightsView;
